save_frequency: 1
name: "vitamin_l2_224_s12.8B_bs90k" 
train_data: '/datasets/datacomp_1b/data/{00000..140089}.tar' # please modify to your own path
train_num_samples: 1_280_000_000
dataset_type: webdataset
precision: 'amp_bfloat16'
warmup: 4436 # 400M
global_batch_size: 90160
batch_size: 0
epochs: 10
lr: 2.0e-3
beta1: 0.9
beta2: 0.95
eps: 1.0e-6
workers: 6
model: "ViTamin-L2"
seed: 0
ddp_static_graph: true
local_loss: true
gather_with_grad: true
force_image_size: 224
grad_checkpointing: true

logs: './logs'
imagenet_val: './imagenet1k/val' # please modify to your own path

report_to: "tensorboard"
log_every_n_steps: 32
zeroshot_steps: 500
val_steps: 500
save_every_n_steps: 500
delete_prev_step_ckpt: true
aug_cfg: {'scale': [0.4, 1.0], 'color_jitter': [0.32, 0.32, 0.32, 0.08], 'color_jitter_prob': 0.8, 'gray_scale_prob': 0.2}
zeroshot_frequency: 1
resume: latest