# arnold 128 gpus
save_frequency: 1
name: "vitamin_base_d14ms128m_bs8k_lr5e4"
train_data: '/datasets/datacomp_1b/data/{00000..00020}.tar'
train_num_samples: 12_800_000
dataset_type: webdataset
precision: 'amp_bfloat16'
warmup: 500
global_batch_size: 16 # 8192 # 32 gpu
batch_size: 0
epochs: 10
lr: 5e-4
beta1: 0.9
beta2: 0.98
eps: 1.0e-6
workers: 4
model: "ViTamin-B"
seed: 0
ddp_static_graph: true
local_loss: true
gather_with_grad: true
force_image_size: 224
grad_checkpointing: true

logs: './logs'
imagenet_val: './imagenet1k/val' # please modify to your own path

report_to: "tensorboard"
log_every_n_steps: 128
zeroshot_steps: 6104
val_steps: 6104
save_every_n_steps: 6104
delete_prev_step_ckpt: true